[package]
name        = "daglib"
version     = "0.1.0"
authors     = ["Matthias Beyer <mail@beyermatthias.de>"]
edition     = "2018"
description = "Generic async DAG library"

[dependencies]
async-trait = "0.1"
futures = "0.3"
thiserror = "1"

[dev-dependencies]
tokio-test = "0.4"

